import { defineConfig } from '@playwright/test';
import dotenv from "dotenv";
import { devices } from "playwright";

// Завантаження змінних середовища
dotenv.config();

const qaseProjectCode = process.env.QASE_PROJECT_CODE;
const qaseRunId = process.env.QASE_TESTOPS_RUN_ID;
export const qaseTestRunLink = `https://app.qase.io/run/${qaseProjectCode}/dashboard/${qaseRunId}`;
const qaseReporter = {
  mode: 'testops',
  debug: true,
  testops: {
    api: {
      token: process.env.QASE_API_TOKEN,
    },
    project: qaseProjectCode,
    uploadAttachments: true,
    run: {
      id: Number(qaseRunId),
      complete: true,
    },
    rootSuite: 'Playwright autogenerated cases'
  },
};

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : 2,
  timeout: 100_000,
  reporter: process.env.CI
      ? [
        ['blob'],
        ['playwright-qase-reporter', qaseReporter],
      ]
      : [
        ['html', { outputFolder: 'playwright-report', open: 'never' }],
        ['list'],
      ],
  use: {
    baseURL: 'http://cloudtwo.cloud-vms.com',
    trace: 'on-first-retry',
    screenshot: `only-on-failure`,
    video: `retain-on-failure`,
    headless: Boolean(process.env.CI),
  },
  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
  ],
  globalSetup: './utils/global-setup.ts',
  globalTeardown: './utils/global-teardown.ts',
});
